# Generated by Django 4.2.3 on 2023-12-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_title_alter_new_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en_us',
            field=models.CharField(help_text='category title', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(help_text='category title', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='new',
            name='text_en_us',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='new',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='new',
            name='title_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='new',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
